import {
  X,
  Copy,
  Settings,
  StopCircle,
  QrCodeIcon,
  TextSelect,
  TextIcon,
  WholeWord,
  Languages,
  Info,
  TrashIcon,
  Mic,
  CloudIcon,
  Check,
  Loader,
  PanelLeftClose,
  PanelTop,
  ArrowDown,
  Link,
  Palette,
  Cog,
  AlignLeft,
  AlignCenter,
  AlignRight,
  ArrowLeftRight,
  RotateCcw,
  Captions,
  FileText,
  Type,
  GripVertical,
} from "lucide-react";

export const Icons = {
  close: X,
  copy: Copy,
  settings: Settings,
  stop: StopCircle,
  qrCode: QrCodeIcon,
  textSelect: TextSelect,
  text: TextIcon,
  wholeWord: WholeWord,
  languages: Languages,
  info: Info,
  trash: TrashIcon,
  mic: Mic,
  cloud: CloudIcon,
  check: Check,
  loader: Loader,
  panelLeftClose: PanelLeftClose,
  panelTop: PanelTop,
  arrowDown: ArrowDown,
  link: Link,
  palette: Palette,
  cog: Cog,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  arrowLeftRight: ArrowLeftRight,
  rotateCcw: RotateCcw,
  captions: Captions,
  fileText: FileText,
  type: Type,
  gripVertical: GripVertical,
};
