import {
  X,
  Copy,
  Settings,
  StopCircle,
  QrCodeIcon,
  TextSelect,
  TextIcon,
  WholeWord,
  Languages,
  Info,
  TrashIcon,
  Mic,
  CloudIcon,
  Check,
  Loader,
} from "lucide-react";

export const Icons = {
  close: X,
  copy: Copy,
  settings: Settings,
  stop: StopCircle,
  qrCode: QrCodeIcon,
  textSelect: TextSelect,
  text: TextIcon,
  wholeWord: WholeWord,
  languages: Languages,
  info: Info,
  trash: TrashIcon,
  mic: Mic,
  cloud: CloudIcon,
  check: Check,
  loader: Loader,
};
